### ISSUE TITLE
Recents Page Displaying K1 Data as K2

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Planet-Hunters-2#260]
The Recents page appears to be displaying some recently classified data as having originated from K2, despite that all of the data currently up for classification is K1.

![screen shot 2014-12-22 at 9 35 44 am](https://cloud.githubusercontent.com/assets/8987864/5526974/1dc59c4c-89bf-11e4-8431-8f9bc5e7b460.png)

A user has also pointed out a few specific examples of K1 objects being marked as K2: http://talk.planethunters.org/#/boards/BPH0000002/discussions/DPH00008fw?page=1&comment_id=549475ca9cd11806b5000921

**Comment by chrissnyder** [comment]
Due to the data that Talk provides to the Recents view, we can't make an accurate determination if a subject is a K1 or K2 subject at that point. The hack that was put in to provide this was shown to not be reliable, hence the incorrectly labeling. So rather than leave incorrect labeling there, I've removed them completely. Sucks, but I think no label is better than an incorrect label.
